### ISSUE TITLE
How to build an LD reference file

### ISSUE THREAD

**Issue by Gujmin** [liangyy/SPrediXcan2PTRS#3]
I did not see any instructions on how to build an LD reference file in the code you provided. Is it necessary to use GTEx variant data, or can other individuals' genomic data be used as a substitute?

**Comment by liangyy** [comment]
Hi!

You can use https://github.com/liangyy/SPrediXcan2PTRS/blob/main/generate_gtex_v8_geno_cov.py. It was written for GTEx V8 data for actually usable for any other data with similar format. The data required is an individual-level LD panel in VCF format along with the predictDB file. Note that internally the script parses `varID` in predictDB file to get the chromosome, position, ref, and alt so please make sure that `varID` in your predictDB is `${chr}_${pos}_${ref}_${alt}`. For the chromosome coding in both VCF and predictDB, use numbers with no prefix (i.e. use `1` rather than `chr1`) and code chromosome X as 23. 

An example 

```
python generate_gtex_v8_geno_cov.py \
  --genotype_vcf [genotype-vcf-file] \
  --predictdb [predictdb-file] \
  --mode evd 0 \
  --sample_list [optional; the list of samples to use from genotype vcf] \
  --output_prefix [output prefix] 
```

About `--mode`, some descriptions about the available options are in  https://github.com/liangyy/SPrediXcan2PTRS/blob/83bc1c6c6fdae7691191f15b2ce2bae5c9f43337/generate_gtex_v8_geno_cov.py#L55-L61. 
At the high level, these are different ways to store the LD matrix:
* `naive`: save as is but you can select using `float32` or `float64` (i.e. `f32` or `f64`) for different precision
* `banded`: save the banded LD matrix (saved as a sparse matrix) where all elements (i, j) with `abs(i - j) > band-size` are zero
* `evd`: save eigen values and eigen vectors of the LD matrix EVD where we only keep the eigen values/vectors with `eigen value > max(eigen value) * min-max-threshold`
* `cap`: save a sparse version of the LD matrix by setting all entries with `abs(value) < threshold-of-cap` to zero. So, the matrix will also be saved as a sparse matrix

Let me know if you have any further questions!
Thanks!

**Comment by Gujmin** [comment]
> Hi!
> 
> You can use https://github.com/liangyy/SPrediXcan2PTRS/blob/main/generate_gtex_v8_geno_cov.py. It was written for GTEx V8 data for actually usable for any other data with similar format. The data required is an individual-level LD panel in VCF format along with the predictDB file. Note that internally the script parses `varID` in predictDB file to get the chromosome, position, ref, and alt so please make sure that `varID` in your predictDB is `${chr}_${pos}_${ref}_${alt}`. For the chromosome coding in both VCF and predictDB, use numbers with no prefix (i.e. use `1` rather than `chr1`) and code chromosome X as 23.
> 
> An example
> 
> ```
> python generate_gtex_v8_geno_cov.py \
>   --genotype_vcf [genotype-vcf-file] \
>   --predictdb [predictdb-file] \
>   --mode evd 0 \
>   --sample_list [optional; the list of samples to use from genotype vcf] \
>   --output_prefix [output prefix] 
> ```
> 
> About `--mode`, some descriptions about the available options are in
> 
> https://github.com/liangyy/SPrediXcan2PTRS/blob/83bc1c6c6fdae7691191f15b2ce2bae5c9f43337/generate_gtex_v8_geno_cov.py#L55-L61
> 
> .
> At the high level, these are different ways to store the LD matrix:
> * `naive`: save as is but you can select using `float32` or `float64` (i.e. `f32` or `f64`) for different precision
> * `banded`: save the banded LD matrix (saved as a sparse matrix) where all elements (i, j) with `abs(i - j) > band-size` are zero
> * `evd`: save eigen values and eigen vectors of the LD matrix EVD where we only keep the eigen values/vectors with `eigen value > max(eigen value) * min-max-threshold`
> * `cap`: save a sparse version of the LD matrix by setting all entries with `abs(value) < threshold-of-cap` to zero. So, the matrix will also be saved as a sparse matrix
> 
> Let me know if you have any further questions! Thanks!

Thank you for your assistance, but I encountered the following error when I ran the code to generate LD reference files.
![202442105556](https://github.com/liangyy/SPrediXcan2PTRS/assets/119839355/9d41c265-364a-47ef-a438-5569bf9455ad)
I would like to inquire if there is an issue with the content of my input VCF file. This is the individual-level LD panel in VCF format  I entered,
![202442105916](https://github.com/liangyy/SPrediXcan2PTRS/assets/119839355/b661ac96-1e96-4e26-aecf-5aa339181f1a)
This is the original hg_38 VCF genotype file.
![20244211147](https://github.com/liangyy/SPrediXcan2PTRS/assets/119839355/c50c83f3-8f1b-4d5d-a8c0-5a8541a49646)
Actually, I have tried both of these VCF files as input files, but the same error occurs.
I used the predictDB file download from the [predictedDB](https://predictdb.org/).

**Comment by liangyy** [comment]
Hi @Gujmin, sorry, I think I described the requirement of chromosome coding wrong (my bad, it's been a while since the last time I worked with these data and this piece of code). I think the correct chromosome coding should be `chrN` instead of integer coding. So, if it is not too much work, you could convert integer coding to chrN in your VCG file. It's possible to make the code more flexible but I don't have the bandwidth to work on it now.

**Comment by Gujmin** [comment]
> Hi @Gujmin, sorry, I think I described the requirement of chromosome coding wrong (my bad, it's been a while since the last time I worked with these data and this piece of code). I think the correct chromosome coding should be `chrN` instead of integer coding. So, if it is not too much work, you could convert integer coding to chrN in your VCG file. It's possible to make the code more flexible but I don't have the bandwidth to work on it now.

Thank you for your continuous help and guidance. I have successfully run the script "generate_gtex_v8_geno_cov.py" and generated results for each chromosome. The format of my input VCF file is as follows:
![20244301213](https://github.com/liangyy/SPrediXcan2PTRS/assets/119839355/c4805f03-003d-4863-8f1d-bec2c4d4d896)

However, when I run the script "run_pxcan2ptrs.py", I encountered an error:
![202443098](https://github.com/liangyy/SPrediXcan2PTRS/assets/119839355/3d62362b-172c-4961-9277-9f5699df5b17)
I'm not sure where the problem lies. Below is my complete code:
```
#!/bin/bash

export PYTHONPATH="/home/gujm/SPrediXcan2PTRS:$PYTHONPATH"
export PYTHONPATH="/home/gujm/transethnic_prs:$PYTHONPATH"

runscript=/home/gujm/SPrediXcan2PTRS/run_pxcan2ptrs.py
pxcan_file=/disk194/gujm/SPrediXcan2PTRS/SprediXcan/height/spredixcan_result/spredixcan_imputed_height_eur__PM__Whole_Blood.csv
predict_db=/disk194/gujm/SPrediXcan2PTRS/trans_hg/data/models/eqtl/mashr/mashr_Whole_Blood.db
geno_cov_file=/disk194/gujm/SPrediXcan2PTRS/SPrediXcan2PTRS/height/mashr_Whole_Blood.geno_cov.*.evd.npz
gwas=/disk194/gujm/SPrediXcan2PTRS/SprediXcan/height/processed_summary_imputation/imputed_height_eur.txt.gz
GWASN=1597374
outdir=/disk194/gujm/SPrediXcan2PTRS/SPrediXcan2PTRS/height
ptrs_prefix=$outdir/SPrediXcan2PTRS_spredixcan_imputed_height_eur_Whole_Blood

  
python $runscript \
--predixcan $pxcan_file \
--predictdb $predict_db \
--gwas $gwas \
--gwas_cols chromosome=chromosome \
            position=position \
            effect_allele=effect_allele \
            non_effect_allele=non_effect_allele \
--gwas_sample_size $GWASN \
--output_prefix $ptrs_prefix \
--original_scale \
--clump
```

**Comment by liangyy** [comment]
Hi @Gujmin, it seems you followed up on some issues with using `run_pxcan2ptrs.py` but apparently this issue lost track on this. I was wondering if you resolved the problem. If not, could you post it again here or open a new issue? Thank you!

**Comment by Gujmin** [comment]
> Hi @Gujmin, it seems you followed up on some issues with using `run_pxcan2ptrs.py` but apparently this issue lost track on this. I was wondering if you resolved the problem. If not, could you post it again here or open a new issue? Thank you!

Thank you for your help, I did encounter a problem before, but I found out that it was an issue with my code. Currently, I am able to run the complete code flow successfully. I sincerely appreciate your help and concern.
But I still have one question: How can I specify Clump-PTRS and S-EN-PTRS in the code, and how can I set the Hyperparameters ?
